"""add posting_date and make jobs description nullable

Revision ID: 0d7648a5ece7
Revises: 0047b0c1c4d7
Create Date: 2026-09-04 10:00:37.927279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7648a5ece7'
down_revision: Union[str, Sequence[str], None] = '0047b0c1c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('posting_date', sa.Date(), nullable=True))
    op.alter_column('Jobs', 'description',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'description',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('Jobs', 'posting_date')
    # ### end Alembic commands ###
