"""create skills tables

Revision ID: 2cbf1ff85165
Revises: 97a3d184389a
Create Date: 2026-08-27 13:15:19.425070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbf1ff85165'
down_revision: Union[str, Sequence[str], None] = '97a3d184389a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Skills_id'), 'Skills', ['id'], unique=False)
    op.create_table('CandidateSkills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['Candidates.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CandidateSkills_id'), 'CandidateSkills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CandidateSkills_id'), table_name='CandidateSkills')
    op.drop_table('CandidateSkills')
    op.drop_index(op.f('ix_Skills_id'), table_name='Skills')
    op.drop_table('Skills')
    # ### end Alembic commands ###
