"""create job skills table

Revision ID: 963e39fc665a
Revises: a7c9bdd88ead
Create Date: 2026-08-27 13:30:48.678322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963e39fc665a'
down_revision: Union[str, Sequence[str], None] = 'a7c9bdd88ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JobSkills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_JobSkills_id'), 'JobSkills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_JobSkills_id'), table_name='JobSkills')
    op.drop_table('JobSkills')
    # ### end Alembic commands ###
