"""create work experience table

Revision ID: 97a3d184389a
Revises: 90846893da52
Create Date: 2026-08-27 13:12:18.859465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a3d184389a'
down_revision: Union[str, Sequence[str], None] = '90846893da52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WorkExperience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['Candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WorkExperience_id'), 'WorkExperience', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_WorkExperience_id'), table_name='WorkExperience')
    op.drop_table('WorkExperience')
    # ### end Alembic commands ###
