"""create jobs table

Revision ID: a7c9bdd88ead
Revises: d7ef08377a04
Create Date: 2026-08-27 13:28:06.327882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c9bdd88ead'
down_revision: Union[str, Sequence[str], None] = 'd7ef08377a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('required_education', sa.String(length=255), nullable=True),
    sa.Column('required_experience_years', sa.Float(), nullable=True),
    sa.Column('experience_description', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Jobs_id'), 'Jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Jobs_id'), table_name='Jobs')
    op.drop_table('Jobs')
    # ### end Alembic commands ###
