"""create language tables

Revision ID: d7301ec4aa4c
Revises: 2cbf1ff85165
Create Date: 2026-08-27 13:23:17.895414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7301ec4aa4c'
down_revision: Union[str, Sequence[str], None] = '2cbf1ff85165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Languages_id'), 'Languages', ['id'], unique=False)
    op.create_table('CandidateLanguages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['Candidates.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['Languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CandidateLanguages_id'), 'CandidateLanguages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CandidateLanguages_id'), table_name='CandidateLanguages')
    op.drop_table('CandidateLanguages')
    op.drop_index(op.f('ix_Languages_id'), table_name='Languages')
    op.drop_table('Languages')
    # ### end Alembic commands ###
