"""create projects table

Revision ID: d7ef08377a04
Revises: d7301ec4aa4c
Create Date: 2026-08-27 13:25:11.288995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ef08377a04'
down_revision: Union[str, Sequence[str], None] = 'd7301ec4aa4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('technologies', sa.String(length=500), nullable=True),
    sa.Column('project_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['Candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Projects_id'), 'Projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Projects_id'), table_name='Projects')
    op.drop_table('Projects')
    # ### end Alembic commands ###
